name: Build wheels

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # if you have git submodules

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.0
        env:
          # Build for Python 3.9-3.12
          CIBW_BUILD: cp39-* cp310-* cp311-* cp312-*

          # Skip 32-bit builds and musl (unless you need them)
          CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux_*"

          # Linux: Build for x86_64 and aarch64
          CIBW_ARCHS_LINUX: x86_64 aarch64

          # macOS: Build for x86_64 and arm64 (Apple Silicon)
          CIBW_ARCHS_MACOS: x86_64 arm64

          # Windows: Just x86_64
          CIBW_ARCHS_WINDOWS: AMD64

          # Install dependencies needed for your build
          CIBW_BEFORE_BUILD: pip install numpy cython # adjust as needed

          # Run tests after building (optional but recommended)
          CIBW_TEST_COMMAND: pytest {project}/tests
          CIBW_TEST_REQUIRES: pytest

      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
